import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { X, Plus, Minus, Trash2, ShoppingBag } from "lucide-react";
import { useCart } from "../../contexts/CartContext";
import { formatCurrency } from "../../types/cart";
import { useNavigate } from "react-router-dom";
const CartSidebar = ({ isOpen, onClose }) => {
    const { cart, removeItem, updateQuantity, getCartSummary, hasItems, isLoading, } = useCart();
    const navigate = useNavigate();
    const summary = getCartSummary();
    const handleCheckout = () => {
        onClose();
        navigate("/checkout");
    };
    const handleQuantityChange = (itemId, newQuantity) => {
        if (newQuantity < 1) {
            removeItem(itemId);
        }
        else {
            updateQuantity(itemId, newQuantity);
        }
    };
    return (_jsxs(_Fragment, { children: [isOpen && (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-50 z-40", onClick: onClose })), _jsxs("div", { className: `
        fixed top-0 right-0 h-full w-96 bg-white shadow-xl z-50 transform transition-transform duration-300 ease-in-out
        ${isOpen ? "translate-x-0" : "translate-x-full"}
      `, children: [_jsxs("div", { className: "flex items-center justify-between p-6 border-b", children: [_jsxs("h2", { className: "text-xl font-bold text-gray-900 flex items-center gap-2", children: [_jsx(ShoppingBag, { className: "w-5 h-5" }), "Carrinho (", summary.itemCount, ")"] }), _jsx("button", { onClick: onClose, className: "p-2 hover:bg-gray-100 rounded-full transition-colors", children: _jsx(X, { className: "w-5 h-5" }) })] }), _jsxs("div", { className: "flex flex-col h-full", children: [_jsx("div", { className: "flex-1 overflow-y-auto p-6", children: !hasItems() ? (_jsxs("div", { className: "flex flex-col items-center justify-center h-full text-gray-500", children: [_jsx(ShoppingBag, { className: "w-16 h-16 mb-4 opacity-50" }), _jsx("p", { className: "text-lg font-medium mb-2", children: "Carrinho vazio" }), _jsx("p", { className: "text-sm text-center", children: "Adicione alguns planos para come\u00E7ar" })] })) : (_jsx("div", { className: "space-y-4", children: cart?.items.map((item) => (_jsxs("div", { className: "bg-gray-50 rounded-lg p-4", children: [_jsxs("div", { className: "flex justify-between items-start mb-3", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "font-semibold text-gray-900 mb-1", children: item.name }), _jsx("p", { className: "text-sm text-gray-600 mb-2", children: item.description }), _jsxs("div", { className: "flex items-center gap-2 text-xs text-gray-500", children: [_jsxs("span", { children: [item.duration, " meses"] }), item.isPopular && (_jsx("span", { className: "bg-blue-100 text-blue-800 px-2 py-1 rounded-full", children: "Popular" }))] })] }), _jsx("button", { onClick: () => removeItem(item.id), className: "p-1 hover:bg-red-100 rounded-full transition-colors text-red-500", disabled: isLoading, children: _jsx(Trash2, { className: "w-4 h-4" }) })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { onClick: () => handleQuantityChange(item.id, item.quantity - 1), className: "p-1 hover:bg-gray-200 rounded-full transition-colors", disabled: isLoading, children: _jsx(Minus, { className: "w-4 h-4" }) }), _jsx("span", { className: "w-8 text-center font-medium", children: item.quantity }), _jsx("button", { onClick: () => handleQuantityChange(item.id, item.quantity + 1), className: "p-1 hover:bg-gray-200 rounded-full transition-colors", disabled: isLoading, children: _jsx(Plus, { className: "w-4 h-4" }) })] }), _jsxs("div", { className: "text-right", children: [_jsx("div", { className: "font-bold text-gray-900", children: formatCurrency(item.price * item.quantity, item.currency) }), item.discount && (_jsxs("div", { className: "text-xs text-green-600", children: ["-", item.discount.type === "percentage"
                                                                        ? `${item.discount.value}%`
                                                                        : formatCurrency(item.discount.value, item.currency)] }))] })] }), item.features && item.features.length > 0 && (_jsxs("div", { className: "mt-3 pt-3 border-t border-gray-200", children: [_jsx("p", { className: "text-xs text-gray-500 mb-1", children: "Inclui:" }), _jsxs("ul", { className: "text-xs text-gray-600 space-y-1", children: [item.features.slice(0, 3).map((feature, index) => (_jsxs("li", { className: "flex items-center gap-1", children: [_jsx("span", { className: "w-1 h-1 bg-gray-400 rounded-full" }), feature] }, index))), item.features.length > 3 && (_jsxs("li", { className: "text-gray-400", children: ["+", item.features.length - 3, " mais"] }))] })] }))] }, item.id))) })) }), hasItems() && (_jsxs("div", { className: "border-t bg-white p-6", children: [_jsxs("div", { className: "space-y-2 mb-4", children: [_jsxs("div", { className: "flex justify-between text-sm", children: [_jsx("span", { children: "Subtotal" }), _jsx("span", { children: formatCurrency(summary.subtotal, summary.currency) })] }), summary.discount > 0 && (_jsxs("div", { className: "flex justify-between text-sm text-green-600", children: [_jsx("span", { children: "Desconto" }), _jsxs("span", { children: ["-", formatCurrency(summary.discount, summary.currency)] })] })), summary.tax > 0 && (_jsxs("div", { className: "flex justify-between text-sm", children: [_jsx("span", { children: "Impostos" }), _jsx("span", { children: formatCurrency(summary.tax, summary.currency) })] })), _jsxs("div", { className: "flex justify-between font-bold text-lg pt-2 border-t", children: [_jsx("span", { children: "Total" }), _jsx("span", { children: formatCurrency(summary.total, summary.currency) })] }), summary.savings && summary.savings > 0 && (_jsxs("div", { className: "text-center text-sm text-green-600", children: ["Voc\u00EA economiza", " ", formatCurrency(summary.savings, summary.currency), "!"] }))] }), _jsxs("div", { className: "space-y-3", children: [_jsx("button", { onClick: handleCheckout, disabled: isLoading, className: "w-full bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white font-semibold py-3 px-4 rounded-lg transition-colors", children: isLoading ? "Processando..." : "Finalizar Compra" }), _jsx("button", { onClick: onClose, className: "w-full border border-gray-300 hover:bg-gray-50 text-gray-700 font-medium py-2 px-4 rounded-lg transition-colors", children: "Continuar Comprando" })] })] }))] })] })] }));
};
export default CartSidebar;
